In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
#reading th data
data=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",encoding='latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
data.shape


(5572, 5)

In [4]:
#drop the unnecessary columns
data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)
data.shape

(5572, 2)

In [5]:
#split the data
# 80% of the data will be in training data and 20% of the data will be in testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data.v2,data.v1,test_size=0.2)

In [6]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4457,)
(4457,)
(1115,)
(1115,)


In [7]:
# CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

#creating an object for CountVectorizer
count_vect=CountVectorizer()

In [8]:
# generate the word counts for the words in the documents
word_count_vector=count_vect.fit(x_train)

# to get the feature names
word_count_vector.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '0789xxxxxxx',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '0870046964

In [9]:
doc_array=word_count_vector.transform(x_train)
doc_array

<4457x7763 sparse matrix of type '<class 'numpy.int64'>'
	with 59140 stored elements in Compressed Sparse Row format>

In [10]:
# converting to a data frame
doc_array=word_count_vector.transform(x_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
#converting the array into a data
feature_matrix=pd.DataFrame(doc_array,columns=word_count_vector.get_feature_names())
feature_matrix

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
4452   0    0       0             0     0     0            0            0   
4453   0    0       0             0     0     0            0            0   
4454   0    0       0             0     0     0            0            0   
4455   0    0       0             0     0     0            0            0   
4456   0    0       0             0     0     0            0            0   

      0125698789  02  ...  ìï  ó_  û_  û_thanks  ûªm  ûªt  ûªve  ûï  ûò  \
0              0   0  ...   0   0   0         0    0    0     0   0   0   
1              0   0  ...   0   0   0         0    0    0     0   0   0   
2              0   0  ...   0   0   0         0    0    0     0   0   0   
3              0   0  ...   0   0   0         0    0    0     0   0   0   
4              0   0  ...   0   0   0         0    0    0     0   0   0   
...          ...  ..  ...  ..  ..  ..       ...  ...  ...   ...  ..  ..   
4452           0   0  ...   0   0   0         0    0    0     0   0   0   
4453           0   0  ...   0   0   0         0    0    0     0   0   0   
4454           0   0  ...   0   0   1         0    0    0     0   0   0   
4455           0   0  ...   0   0   0         0    0    0     0   0   0   
4456           0   0  ...   0   0   0         0    0    0     0   0   0   

      ûówell  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
4452       0  
4453       0  
4454       0  
4455       0  
4456       0  

[4457 rows x 7763 columns]

#### Why fit_transform is performed only on training data?

- Now if we specifically talk about CountVectorizer, then consider the following example, let your training data have the following 3 sentences:
     1. Dog is black.
     2. Sky is blue.
     3. Dog is dancing.
- Now the vocabulary set for this will be {Dog, is, black, sky, blue, dancing}. Now the algorithm that you will train will try to learn rules based on the count of these 6 vocabulary terms. So your features will be vectors of length 6.
- Now if the test set is as follows:
     1. Dog is white.
     2. Sky is black.
- Now if you use the test data for fit_transform your vocabulary will look like {Dog, white, is, Sky, black}. So here your each document will be represented by a vector of length 5 denoting the counts of each of these terms. Now, this will be like comparing apples with oranges. You learn rules for counts of the previous vocabulary and those rules can not be applied to this vocabulary. This is the reason why you only fit on the training data.



In [15]:
# TFIDF vectorizer

#import TFIDF vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

#initialise an object for the TFIDF vectorizer
tfidf=TfidfVectorizer()

In [17]:
#apply the tfidf to the data(x_train)

x_train_transformed=tfidf.fit_transform(x_train)
x_train_transformed

<4457x7763 sparse matrix of type '<class 'numpy.float64'>'
	with 59140 stored elements in Compressed Sparse Row format>

In [19]:
x_test_transformed=tfidf.transform(x_test)
x_test_transformed

<1115x7763 sparse matrix of type '<class 'numpy.float64'>'
	with 13803 stored elements in Compressed Sparse Row format>

In [20]:
# to see the feature name
tfidf.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '0789xxxxxxx',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '0870046964

In [22]:
#position of the words in the sparse matrix
tfidf.vocabulary_

{'what': 7470,
 'do': 2369,
 'want': 7370,
 'when': 7477,
 'come': 1900,
 'back': 1193,
 'beautiful': 1276,
 'necklace': 4749,
 'as': 1082,
 'token': 6947,
 'of': 4916,
 'my': 4690,
 'heart': 3384,
 'for': 2945,
 'you': 7705,
 'thats': 6809,
 'will': 7515,
 'give': 3144,
 'but': 1566,
 'only': 4968,
 'to': 6933,
 'wife': 7507,
 'liking': 4139,
 'be': 1270,
 'that': 6806,
 'and': 956,
 'see': 5986,
 'no': 4819,
 'one': 4962,
 'can': 1623,
 'dont': 2405,
 'call': 1599,
 'me': 4429,
 'wait': 7346,
 'till': 6898,
 'wow': 7613,
 'the': 6812,
 'boys': 1468,
 'take': 6688,
 '2007': 356,
 'uk': 7121,
 'tour': 7000,
 'win': 7518,
 'vip': 7291,
 'tickets': 6890,
 'pre': 5390,
 'book': 1418,
 'with': 7544,
 'club': 1849,
 'txt': 7097,
 '81303': 643,
 'trackmarque': 7006,
 'ltd': 4265,
 'info': 3681,
 'vipclub4u': 7292,
 'emailed': 2565,
 'yifeng': 7696,
 'part': 5106,
 'oredi': 5006,
 'ì_': 7750,
 'get': 3119,
 'it': 3770,
 'fr': 2976,
 'him': 3438,
 'had': 3297,
 'your': 7711,
 'mobile': 4565,
 

In [23]:
#IDF of the terms
tfidf.idf_

array([7.32301397, 6.18357969, 8.70930833, ..., 8.70930833, 7.61069604,
       8.70930833])

In [24]:
# apply the native bayes algorithm

#import BernNB
from sklearn.naive_bayes import BernoulliNB

#creating an object for BerNB
model_BernNB=BernoulliNB()

In [26]:
# applying the algorithm to the data
# objectname.fit(input,output)

model_BernNB.fit(x_train_transformed,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [28]:
#prediction on test data
# syntax: objectname.predict(inputvalues)
y_test_pred=model_BernNB.predict(x_test_transformed)

In [29]:
# compare the actual value(y_test) with predicted values(y_test_pred)
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_test_pred)

array([[974,   0],
       [ 23, 118]], dtype=int64)

In [30]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       974
        spam       1.00      0.84      0.91       141

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [33]:
# test a single message-->spam or ham
new_message=pd.Series('last few days to collect the free entry passes with 40% discount')

#calculate tfidf values for the new message
new_message_transformed=tfidf.transform(new_message)

In [35]:
# predict the new message
model_BernNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')

In [ ]:
# nltk-->text data