In [1]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

90
0.2576637810412099


In [2]:
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))#3 dimensional array

[86 69 92]
[[54 30 23 57]
 [97 56 93 28]
 [37 32  0 43]]
[[[10 72]
  [84 94]
  [25  3]
  [11 29]]

 [[76 52]
  [74 28]
  [23 55]
  [57 44]]

 [[ 1 90]
  [ 6 62]
  [ 1 41]
  [24 30]]]


In [3]:
#creating an array with float values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.5715806675526562
[0.18392927 0.42526054 0.33510183]
[[0.42438461 0.14621252 0.33072735]
 [0.29216331 0.25331524 0.80315454]]


In [5]:
a=random.randint(100,size=(3,2)).ravel()
a

array([13, 91, 35, 11, 13,  2])

In [6]:
#when u r using choice() the array should be on dimensional
random.choice(a)

11

In [8]:
#using choice generate array from list of elements with diff shape using size function
random.choice([1,2,3,4,5],size=(4,4))

array([[3, 5, 4, 3],
       [3, 4, 3, 1],
       [5, 4, 1, 4],
       [5, 4, 2, 4]])

# pandas:
1. data manipulation,analysis and cleaning
2. tabular,unlabelled

# creating a dataframe
1. using 2 dictionaries
2. using simple dictionary 
3. using series

In [15]:
#creating a data frame using 2 dictionaries
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"first":dict1,"second":dict2}
#df=pd.DataFrame(data)
df=pd.DataFrame(data,dtype=np.int32)#changing the data type to int
#when dic key is different u cant change its data type
df


first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [17]:
#using simple dictionary we can create a data frame
d1={"name":["satya","ruch","nithya","harshi"],"address":["hyd","bang","bang","bang"]}
df1=pd.DataFrame(d1)
df1

name address
0   satya     hyd
1    ruch    bang
2  nithya    bang
3  harshi    bang

In [20]:
#using series-->s should be in uppercase
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [22]:
#extracting single column
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [23]:
#extracting multpile coulumns from dataframe
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

# extracting the data from dataframe
1. l0c-->loc[row index,column]
2. iloc-->iloc[row index,column index]

In [24]:
#using loc extracting single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [27]:
#using loc to extract data from multiple columns
#df3.loc[:,["column1","column2"]]
df3.loc[0:5,["column1","column2"]] #this gives 0 to 5 indexes values as output

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [28]:
#using iloc 
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [29]:
df3.iloc[0:4,0:4]

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d

# retrieving the data from dataframe
1. shape
2. column
3. index


In [30]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [32]:
df3.shape

(10, 3)

In [33]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [34]:
df3.index

RangeIndex(start=0, stop=10, step=1)

# viewing data from dataframe
1. head()
2. tail()
3. sample()

In [36]:
df3.head() #frst 5 rows of the data will be displayed

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [38]:
#if u want particular no of rows to be displayed
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [37]:
df3.tail()#last m5 rows will be returned

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [39]:
#if u want particular number of rows using tail
df3.tail(3)

column1  column2 column3
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [40]:
# using sample()-->returns random row
df3.sample()

column1  column2 column3
1        2    23.34       b

In [41]:
#if u want 2 random rows using sample()
df3.sample(2)

column1  column2 column3
0        1    12.23       a
9       10    23.00       j

In [42]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [45]:
#changing or renaming the column names
df3=df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j